site_name: WebApiDocumentation
site_url: https://motttt.github.io/WebApiDocumentation/

site_description: Documentation for use of web APIs
site_author: Noah Mbude

plugins:
    - search
    - swagger-ui-tag

theme:
  name: readthedocs
  analytics:
    gtag: G-72998NWP0W

nav:
  - 'Introduction':
    - apiOperationList.md
    - onboardingProcess.md
    - simulator.md
    - authorisation.md
    - errorCodes.md
  - 'Service API':
    - serviceSpecification.md
